### ISSUE TITLE
is it possible to list / update / delete transactions via the API?

### ISSUE THREAD

**Issue by vesper8** [subbe/waveapp#1]
I know this is just a wrapper for the official API and I appreciate it very much! Thanks for making it!

I would like to use the API to list / update / delete my own personal transactions. From reading the API reference it doesn't appear that this is possible, I was wondering if you could be so kind to confirm whether that's currently the case.

Thank you!

**Comment by subbe** [comment]
Hi.

I am not very sure about this, I don't think it is possible to manipulate transactions through the API. 
You can create a transaction using the _moneyTransactionCreate_ mutation, but can't edit or delete them.
